2015726103_hw1 : disk.o fs.o testcase.o validate.o
	gcc -o 2015726103_hw1 disk.o fs.o testcase.o validate.o

disk.o : disk.c
	gcc -c -o disk.o disk.c

fs.o : fs.c
	gcc -c -o fs.o fs.c




testcase.o : testcase.c
	gcc -c -o testcase.o testcase.c

clean :
	2015726103_hw1
